webtalk_init -webtalk_dir F:/vivado/shiyan/AWS_aes3/zhuchengxu/AWS_aes/AWS_aes.sim/sim_1/behav/xsim/xsim.dir/AWS_aes_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 31 10:07:40 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "924c2c0e-92ae-4353-82d9-eab724d4533d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "94413ddf38c945fc9ff03aa0f06a71bf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "604732 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "13.74_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18028_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4084135603 -regid "" -xml F:/vivado/shiyan/AWS_aes3/zhuchengxu/AWS_aes/AWS_aes.sim/sim_1/behav/xsim/xsim.dir/AWS_aes_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/vivado/shiyan/AWS_aes3/zhuchengxu/AWS_aes/AWS_aes.sim/sim_1/behav/xsim/xsim.dir/AWS_aes_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/vivado/shiyan/AWS_aes3/zhuchengxu/AWS_aes/AWS_aes.sim/sim_1/behav/xsim/xsim.dir/AWS_aes_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
